files:
  - source: /main/en-US/*.json
    translation: /main/%locale%/%original_file_name%

  - source: /settings/en-US.json
    translation: /settings/%locale%.json

  - source: /newtab/en-US.json
    translation: /newtab/%locale%.json

  - source: /welcome/en-US.json
    translation: /welcome/%locale%.json

  - source: /stub-win64-installer/en-US.json
    translation: /stub-win64-installer/%locale%.json

